// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protoc-gen-orm/orm/orm.proto

package orm

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OrmFileOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrmFileOptions) Reset()         { *m = OrmFileOptions{} }
func (m *OrmFileOptions) String() string { return proto.CompactTextString(m) }
func (*OrmFileOptions) ProtoMessage()    {}
func (*OrmFileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{0}
}
func (m *OrmFileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrmFileOptions.Unmarshal(m, b)
}
func (m *OrmFileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrmFileOptions.Marshal(b, m, deterministic)
}
func (m *OrmFileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrmFileOptions.Merge(m, src)
}
func (m *OrmFileOptions) XXX_Size() int {
	return xxx_messageInfo_OrmFileOptions.Size(m)
}
func (m *OrmFileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OrmFileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OrmFileOptions proto.InternalMessageInfo

type OrmMessageOptions struct {
	Ormable              bool          `protobuf:"varint,1,opt,name=ormable,proto3" json:"ormable,omitempty"`
	Include              []*ExtraField `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Table                string        `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	MultiAccount         bool          `protobuf:"varint,4,opt,name=multi_account,json=multiAccount,proto3" json:"multi_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrmMessageOptions) Reset()         { *m = OrmMessageOptions{} }
func (m *OrmMessageOptions) String() string { return proto.CompactTextString(m) }
func (*OrmMessageOptions) ProtoMessage()    {}
func (*OrmMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{1}
}
func (m *OrmMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrmMessageOptions.Unmarshal(m, b)
}
func (m *OrmMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrmMessageOptions.Marshal(b, m, deterministic)
}
func (m *OrmMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrmMessageOptions.Merge(m, src)
}
func (m *OrmMessageOptions) XXX_Size() int {
	return xxx_messageInfo_OrmMessageOptions.Size(m)
}
func (m *OrmMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OrmMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OrmMessageOptions proto.InternalMessageInfo

func (m *OrmMessageOptions) GetOrmable() bool {
	if m != nil {
		return m.Ormable
	}
	return false
}

func (m *OrmMessageOptions) GetInclude() []*ExtraField {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *OrmMessageOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *OrmMessageOptions) GetMultiAccount() bool {
	if m != nil {
		return m.MultiAccount
	}
	return false
}

type ExtraField struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  *OrmTag  `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Package              string   `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtraField) Reset()         { *m = ExtraField{} }
func (m *ExtraField) String() string { return proto.CompactTextString(m) }
func (*ExtraField) ProtoMessage()    {}
func (*ExtraField) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{2}
}
func (m *ExtraField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraField.Unmarshal(m, b)
}
func (m *ExtraField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraField.Marshal(b, m, deterministic)
}
func (m *ExtraField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraField.Merge(m, src)
}
func (m *ExtraField) XXX_Size() int {
	return xxx_messageInfo_ExtraField.Size(m)
}
func (m *ExtraField) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraField.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraField proto.InternalMessageInfo

func (m *ExtraField) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ExtraField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExtraField) GetTag() *OrmTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *ExtraField) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

type OrmFieldOptions struct {
	Tag  *OrmTag `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Drop bool    `protobuf:"varint,2,opt,name=drop,proto3" json:"drop,omitempty"`
	// Types that are valid to be assigned to Association:
	//	*OrmFieldOptions_HasOne
	//	*OrmFieldOptions_BelongsTo
	//	*OrmFieldOptions_HasMany
	//	*OrmFieldOptions_ManyToMany
	Association          isOrmFieldOptions_Association `protobuf_oneof:"association"`
	ReferenceOf          string                        `protobuf:"bytes,7,opt,name=reference_of,json=referenceOf,proto3" json:"reference_of,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OrmFieldOptions) Reset()         { *m = OrmFieldOptions{} }
func (m *OrmFieldOptions) String() string { return proto.CompactTextString(m) }
func (*OrmFieldOptions) ProtoMessage()    {}
func (*OrmFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{3}
}
func (m *OrmFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrmFieldOptions.Unmarshal(m, b)
}
func (m *OrmFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrmFieldOptions.Marshal(b, m, deterministic)
}
func (m *OrmFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrmFieldOptions.Merge(m, src)
}
func (m *OrmFieldOptions) XXX_Size() int {
	return xxx_messageInfo_OrmFieldOptions.Size(m)
}
func (m *OrmFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OrmFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OrmFieldOptions proto.InternalMessageInfo

type isOrmFieldOptions_Association interface {
	isOrmFieldOptions_Association()
}

type OrmFieldOptions_HasOne struct {
	HasOne *HasOneOptions `protobuf:"bytes,3,opt,name=has_one,json=hasOne,proto3,oneof" json:"has_one,omitempty"`
}
type OrmFieldOptions_BelongsTo struct {
	BelongsTo *BelongsToOptions `protobuf:"bytes,4,opt,name=belongs_to,json=belongsTo,proto3,oneof" json:"belongs_to,omitempty"`
}
type OrmFieldOptions_HasMany struct {
	HasMany *HasManyOptions `protobuf:"bytes,5,opt,name=has_many,json=hasMany,proto3,oneof" json:"has_many,omitempty"`
}
type OrmFieldOptions_ManyToMany struct {
	ManyToMany *ManyToManyOptions `protobuf:"bytes,6,opt,name=many_to_many,json=manyToMany,proto3,oneof" json:"many_to_many,omitempty"`
}

func (*OrmFieldOptions_HasOne) isOrmFieldOptions_Association()     {}
func (*OrmFieldOptions_BelongsTo) isOrmFieldOptions_Association()  {}
func (*OrmFieldOptions_HasMany) isOrmFieldOptions_Association()    {}
func (*OrmFieldOptions_ManyToMany) isOrmFieldOptions_Association() {}

func (m *OrmFieldOptions) GetAssociation() isOrmFieldOptions_Association {
	if m != nil {
		return m.Association
	}
	return nil
}

func (m *OrmFieldOptions) GetTag() *OrmTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *OrmFieldOptions) GetDrop() bool {
	if m != nil {
		return m.Drop
	}
	return false
}

func (m *OrmFieldOptions) GetHasOne() *HasOneOptions {
	if x, ok := m.GetAssociation().(*OrmFieldOptions_HasOne); ok {
		return x.HasOne
	}
	return nil
}

func (m *OrmFieldOptions) GetBelongsTo() *BelongsToOptions {
	if x, ok := m.GetAssociation().(*OrmFieldOptions_BelongsTo); ok {
		return x.BelongsTo
	}
	return nil
}

func (m *OrmFieldOptions) GetHasMany() *HasManyOptions {
	if x, ok := m.GetAssociation().(*OrmFieldOptions_HasMany); ok {
		return x.HasMany
	}
	return nil
}

func (m *OrmFieldOptions) GetManyToMany() *ManyToManyOptions {
	if x, ok := m.GetAssociation().(*OrmFieldOptions_ManyToMany); ok {
		return x.ManyToMany
	}
	return nil
}

func (m *OrmFieldOptions) GetReferenceOf() string {
	if m != nil {
		return m.ReferenceOf
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OrmFieldOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OrmFieldOptions_HasOne)(nil),
		(*OrmFieldOptions_BelongsTo)(nil),
		(*OrmFieldOptions_HasMany)(nil),
		(*OrmFieldOptions_ManyToMany)(nil),
	}
}

type OrmTag struct {
	Column                         string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Type                           string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Size_                          int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Precision                      int32    `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
	PrimaryKey                     bool     `protobuf:"varint,5,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Unique                         bool     `protobuf:"varint,6,opt,name=unique,proto3" json:"unique,omitempty"`
	Default                        string   `protobuf:"bytes,7,opt,name=default,proto3" json:"default,omitempty"`
	NotNull                        bool     `protobuf:"varint,8,opt,name=not_null,json=notNull,proto3" json:"not_null,omitempty"`
	AutoIncrement                  bool     `protobuf:"varint,9,opt,name=auto_increment,json=autoIncrement,proto3" json:"auto_increment,omitempty"`
	Index                          string   `protobuf:"bytes,10,opt,name=index,proto3" json:"index,omitempty"`
	UniqueIndex                    string   `protobuf:"bytes,11,opt,name=unique_index,json=uniqueIndex,proto3" json:"unique_index,omitempty"`
	Embedded                       bool     `protobuf:"varint,12,opt,name=embedded,proto3" json:"embedded,omitempty"`
	EmbeddedPrefix                 string   `protobuf:"bytes,13,opt,name=embedded_prefix,json=embeddedPrefix,proto3" json:"embedded_prefix,omitempty"`
	Ignore                         bool     `protobuf:"varint,14,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Foreignkey                     string   `protobuf:"bytes,15,opt,name=foreignkey,proto3" json:"foreignkey,omitempty"`
	AssociationForeignkey          string   `protobuf:"bytes,16,opt,name=association_foreignkey,json=associationForeignkey,proto3" json:"association_foreignkey,omitempty"`
	ManyToMany                     string   `protobuf:"bytes,17,opt,name=many_to_many,json=manyToMany,proto3" json:"many_to_many,omitempty"`
	JointableForeignkey            string   `protobuf:"bytes,18,opt,name=jointable_foreignkey,json=jointableForeignkey,proto3" json:"jointable_foreignkey,omitempty"`
	AssociationJointableForeignkey string   `protobuf:"bytes,19,opt,name=association_jointable_foreignkey,json=associationJointableForeignkey,proto3" json:"association_jointable_foreignkey,omitempty"`
	AssociationAutoupdate          bool     `protobuf:"varint,20,opt,name=association_autoupdate,json=associationAutoupdate,proto3" json:"association_autoupdate,omitempty"`
	AssociationAutocreate          bool     `protobuf:"varint,21,opt,name=association_autocreate,json=associationAutocreate,proto3" json:"association_autocreate,omitempty"`
	AssociationSaveReference       bool     `protobuf:"varint,22,opt,name=association_save_reference,json=associationSaveReference,proto3" json:"association_save_reference,omitempty"`
	Preload                        bool     `protobuf:"varint,23,opt,name=preload,proto3" json:"preload,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *OrmTag) Reset()         { *m = OrmTag{} }
func (m *OrmTag) String() string { return proto.CompactTextString(m) }
func (*OrmTag) ProtoMessage()    {}
func (*OrmTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{4}
}
func (m *OrmTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrmTag.Unmarshal(m, b)
}
func (m *OrmTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrmTag.Marshal(b, m, deterministic)
}
func (m *OrmTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrmTag.Merge(m, src)
}
func (m *OrmTag) XXX_Size() int {
	return xxx_messageInfo_OrmTag.Size(m)
}
func (m *OrmTag) XXX_DiscardUnknown() {
	xxx_messageInfo_OrmTag.DiscardUnknown(m)
}

var xxx_messageInfo_OrmTag proto.InternalMessageInfo

func (m *OrmTag) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *OrmTag) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OrmTag) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *OrmTag) GetPrecision() int32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *OrmTag) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *OrmTag) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *OrmTag) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *OrmTag) GetNotNull() bool {
	if m != nil {
		return m.NotNull
	}
	return false
}

func (m *OrmTag) GetAutoIncrement() bool {
	if m != nil {
		return m.AutoIncrement
	}
	return false
}

func (m *OrmTag) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *OrmTag) GetUniqueIndex() string {
	if m != nil {
		return m.UniqueIndex
	}
	return ""
}

func (m *OrmTag) GetEmbedded() bool {
	if m != nil {
		return m.Embedded
	}
	return false
}

func (m *OrmTag) GetEmbeddedPrefix() string {
	if m != nil {
		return m.EmbeddedPrefix
	}
	return ""
}

func (m *OrmTag) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *OrmTag) GetForeignkey() string {
	if m != nil {
		return m.Foreignkey
	}
	return ""
}

func (m *OrmTag) GetAssociationForeignkey() string {
	if m != nil {
		return m.AssociationForeignkey
	}
	return ""
}

func (m *OrmTag) GetManyToMany() string {
	if m != nil {
		return m.ManyToMany
	}
	return ""
}

func (m *OrmTag) GetJointableForeignkey() string {
	if m != nil {
		return m.JointableForeignkey
	}
	return ""
}

func (m *OrmTag) GetAssociationJointableForeignkey() string {
	if m != nil {
		return m.AssociationJointableForeignkey
	}
	return ""
}

func (m *OrmTag) GetAssociationAutoupdate() bool {
	if m != nil {
		return m.AssociationAutoupdate
	}
	return false
}

func (m *OrmTag) GetAssociationAutocreate() bool {
	if m != nil {
		return m.AssociationAutocreate
	}
	return false
}

func (m *OrmTag) GetAssociationSaveReference() bool {
	if m != nil {
		return m.AssociationSaveReference
	}
	return false
}

func (m *OrmTag) GetPreload() bool {
	if m != nil {
		return m.Preload
	}
	return false
}

type HasOneOptions struct {
	Foreignkey               string   `protobuf:"bytes,1,opt,name=foreignkey,proto3" json:"foreignkey,omitempty"`
	ForeignkeyTag            *OrmTag  `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag,proto3" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey    string   `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey,proto3" json:"association_foreignkey,omitempty"`
	AssociationAutoupdate    bool     `protobuf:"varint,4,opt,name=association_autoupdate,json=associationAutoupdate,proto3" json:"association_autoupdate,omitempty"`
	AssociationAutocreate    bool     `protobuf:"varint,5,opt,name=association_autocreate,json=associationAutocreate,proto3" json:"association_autocreate,omitempty"`
	AssociationSaveReference bool     `protobuf:"varint,6,opt,name=association_save_reference,json=associationSaveReference,proto3" json:"association_save_reference,omitempty"`
	Preload                  bool     `protobuf:"varint,7,opt,name=preload,proto3" json:"preload,omitempty"`
	Replace                  bool     `protobuf:"varint,8,opt,name=replace,proto3" json:"replace,omitempty"`
	Append                   bool     `protobuf:"varint,9,opt,name=append,proto3" json:"append,omitempty"`
	Clear                    bool     `protobuf:"varint,10,opt,name=clear,proto3" json:"clear,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *HasOneOptions) Reset()         { *m = HasOneOptions{} }
func (m *HasOneOptions) String() string { return proto.CompactTextString(m) }
func (*HasOneOptions) ProtoMessage()    {}
func (*HasOneOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{5}
}
func (m *HasOneOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasOneOptions.Unmarshal(m, b)
}
func (m *HasOneOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasOneOptions.Marshal(b, m, deterministic)
}
func (m *HasOneOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasOneOptions.Merge(m, src)
}
func (m *HasOneOptions) XXX_Size() int {
	return xxx_messageInfo_HasOneOptions.Size(m)
}
func (m *HasOneOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_HasOneOptions.DiscardUnknown(m)
}

var xxx_messageInfo_HasOneOptions proto.InternalMessageInfo

func (m *HasOneOptions) GetForeignkey() string {
	if m != nil {
		return m.Foreignkey
	}
	return ""
}

func (m *HasOneOptions) GetForeignkeyTag() *OrmTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *HasOneOptions) GetAssociationForeignkey() string {
	if m != nil {
		return m.AssociationForeignkey
	}
	return ""
}

func (m *HasOneOptions) GetAssociationAutoupdate() bool {
	if m != nil {
		return m.AssociationAutoupdate
	}
	return false
}

func (m *HasOneOptions) GetAssociationAutocreate() bool {
	if m != nil {
		return m.AssociationAutocreate
	}
	return false
}

func (m *HasOneOptions) GetAssociationSaveReference() bool {
	if m != nil {
		return m.AssociationSaveReference
	}
	return false
}

func (m *HasOneOptions) GetPreload() bool {
	if m != nil {
		return m.Preload
	}
	return false
}

func (m *HasOneOptions) GetReplace() bool {
	if m != nil {
		return m.Replace
	}
	return false
}

func (m *HasOneOptions) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

func (m *HasOneOptions) GetClear() bool {
	if m != nil {
		return m.Clear
	}
	return false
}

type BelongsToOptions struct {
	Foreignkey               string   `protobuf:"bytes,1,opt,name=foreignkey,proto3" json:"foreignkey,omitempty"`
	ForeignkeyTag            *OrmTag  `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag,proto3" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey    string   `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey,proto3" json:"association_foreignkey,omitempty"`
	AssociationAutoupdate    bool     `protobuf:"varint,4,opt,name=association_autoupdate,json=associationAutoupdate,proto3" json:"association_autoupdate,omitempty"`
	AssociationAutocreate    bool     `protobuf:"varint,5,opt,name=association_autocreate,json=associationAutocreate,proto3" json:"association_autocreate,omitempty"`
	AssociationSaveReference bool     `protobuf:"varint,6,opt,name=association_save_reference,json=associationSaveReference,proto3" json:"association_save_reference,omitempty"`
	Preload                  bool     `protobuf:"varint,7,opt,name=preload,proto3" json:"preload,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *BelongsToOptions) Reset()         { *m = BelongsToOptions{} }
func (m *BelongsToOptions) String() string { return proto.CompactTextString(m) }
func (*BelongsToOptions) ProtoMessage()    {}
func (*BelongsToOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{6}
}
func (m *BelongsToOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BelongsToOptions.Unmarshal(m, b)
}
func (m *BelongsToOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BelongsToOptions.Marshal(b, m, deterministic)
}
func (m *BelongsToOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BelongsToOptions.Merge(m, src)
}
func (m *BelongsToOptions) XXX_Size() int {
	return xxx_messageInfo_BelongsToOptions.Size(m)
}
func (m *BelongsToOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BelongsToOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BelongsToOptions proto.InternalMessageInfo

func (m *BelongsToOptions) GetForeignkey() string {
	if m != nil {
		return m.Foreignkey
	}
	return ""
}

func (m *BelongsToOptions) GetForeignkeyTag() *OrmTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *BelongsToOptions) GetAssociationForeignkey() string {
	if m != nil {
		return m.AssociationForeignkey
	}
	return ""
}

func (m *BelongsToOptions) GetAssociationAutoupdate() bool {
	if m != nil {
		return m.AssociationAutoupdate
	}
	return false
}

func (m *BelongsToOptions) GetAssociationAutocreate() bool {
	if m != nil {
		return m.AssociationAutocreate
	}
	return false
}

func (m *BelongsToOptions) GetAssociationSaveReference() bool {
	if m != nil {
		return m.AssociationSaveReference
	}
	return false
}

func (m *BelongsToOptions) GetPreload() bool {
	if m != nil {
		return m.Preload
	}
	return false
}

type HasManyOptions struct {
	Foreignkey               string   `protobuf:"bytes,1,opt,name=foreignkey,proto3" json:"foreignkey,omitempty"`
	ForeignkeyTag            *OrmTag  `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag,proto3" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey    string   `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey,proto3" json:"association_foreignkey,omitempty"`
	PositionField            string   `protobuf:"bytes,4,opt,name=position_field,json=positionField,proto3" json:"position_field,omitempty"`
	PositionFieldTag         *OrmTag  `protobuf:"bytes,5,opt,name=position_field_tag,json=positionFieldTag,proto3" json:"position_field_tag,omitempty"`
	AssociationAutoupdate    bool     `protobuf:"varint,6,opt,name=association_autoupdate,json=associationAutoupdate,proto3" json:"association_autoupdate,omitempty"`
	AssociationAutocreate    bool     `protobuf:"varint,7,opt,name=association_autocreate,json=associationAutocreate,proto3" json:"association_autocreate,omitempty"`
	AssociationSaveReference bool     `protobuf:"varint,8,opt,name=association_save_reference,json=associationSaveReference,proto3" json:"association_save_reference,omitempty"`
	Preload                  bool     `protobuf:"varint,9,opt,name=preload,proto3" json:"preload,omitempty"`
	Replace                  bool     `protobuf:"varint,10,opt,name=replace,proto3" json:"replace,omitempty"`
	Append                   bool     `protobuf:"varint,11,opt,name=append,proto3" json:"append,omitempty"`
	Clear                    bool     `protobuf:"varint,12,opt,name=clear,proto3" json:"clear,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *HasManyOptions) Reset()         { *m = HasManyOptions{} }
func (m *HasManyOptions) String() string { return proto.CompactTextString(m) }
func (*HasManyOptions) ProtoMessage()    {}
func (*HasManyOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{7}
}
func (m *HasManyOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasManyOptions.Unmarshal(m, b)
}
func (m *HasManyOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasManyOptions.Marshal(b, m, deterministic)
}
func (m *HasManyOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasManyOptions.Merge(m, src)
}
func (m *HasManyOptions) XXX_Size() int {
	return xxx_messageInfo_HasManyOptions.Size(m)
}
func (m *HasManyOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_HasManyOptions.DiscardUnknown(m)
}

var xxx_messageInfo_HasManyOptions proto.InternalMessageInfo

func (m *HasManyOptions) GetForeignkey() string {
	if m != nil {
		return m.Foreignkey
	}
	return ""
}

func (m *HasManyOptions) GetForeignkeyTag() *OrmTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *HasManyOptions) GetAssociationForeignkey() string {
	if m != nil {
		return m.AssociationForeignkey
	}
	return ""
}

func (m *HasManyOptions) GetPositionField() string {
	if m != nil {
		return m.PositionField
	}
	return ""
}

func (m *HasManyOptions) GetPositionFieldTag() *OrmTag {
	if m != nil {
		return m.PositionFieldTag
	}
	return nil
}

func (m *HasManyOptions) GetAssociationAutoupdate() bool {
	if m != nil {
		return m.AssociationAutoupdate
	}
	return false
}

func (m *HasManyOptions) GetAssociationAutocreate() bool {
	if m != nil {
		return m.AssociationAutocreate
	}
	return false
}

func (m *HasManyOptions) GetAssociationSaveReference() bool {
	if m != nil {
		return m.AssociationSaveReference
	}
	return false
}

func (m *HasManyOptions) GetPreload() bool {
	if m != nil {
		return m.Preload
	}
	return false
}

func (m *HasManyOptions) GetReplace() bool {
	if m != nil {
		return m.Replace
	}
	return false
}

func (m *HasManyOptions) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

func (m *HasManyOptions) GetClear() bool {
	if m != nil {
		return m.Clear
	}
	return false
}

type ManyToManyOptions struct {
	Jointable                      string   `protobuf:"bytes,1,opt,name=jointable,proto3" json:"jointable,omitempty"`
	Foreignkey                     string   `protobuf:"bytes,2,opt,name=foreignkey,proto3" json:"foreignkey,omitempty"`
	JointableForeignkey            string   `protobuf:"bytes,3,opt,name=jointable_foreignkey,json=jointableForeignkey,proto3" json:"jointable_foreignkey,omitempty"`
	AssociationForeignkey          string   `protobuf:"bytes,4,opt,name=association_foreignkey,json=associationForeignkey,proto3" json:"association_foreignkey,omitempty"`
	AssociationJointableForeignkey string   `protobuf:"bytes,5,opt,name=association_jointable_foreignkey,json=associationJointableForeignkey,proto3" json:"association_jointable_foreignkey,omitempty"`
	AssociationAutoupdate          bool     `protobuf:"varint,6,opt,name=association_autoupdate,json=associationAutoupdate,proto3" json:"association_autoupdate,omitempty"`
	AssociationAutocreate          bool     `protobuf:"varint,7,opt,name=association_autocreate,json=associationAutocreate,proto3" json:"association_autocreate,omitempty"`
	AssociationSaveReference       bool     `protobuf:"varint,8,opt,name=association_save_reference,json=associationSaveReference,proto3" json:"association_save_reference,omitempty"`
	Preload                        bool     `protobuf:"varint,9,opt,name=preload,proto3" json:"preload,omitempty"`
	Replace                        bool     `protobuf:"varint,10,opt,name=replace,proto3" json:"replace,omitempty"`
	Append                         bool     `protobuf:"varint,11,opt,name=append,proto3" json:"append,omitempty"`
	Clear                          bool     `protobuf:"varint,13,opt,name=clear,proto3" json:"clear,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *ManyToManyOptions) Reset()         { *m = ManyToManyOptions{} }
func (m *ManyToManyOptions) String() string { return proto.CompactTextString(m) }
func (*ManyToManyOptions) ProtoMessage()    {}
func (*ManyToManyOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{8}
}
func (m *ManyToManyOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManyToManyOptions.Unmarshal(m, b)
}
func (m *ManyToManyOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManyToManyOptions.Marshal(b, m, deterministic)
}
func (m *ManyToManyOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManyToManyOptions.Merge(m, src)
}
func (m *ManyToManyOptions) XXX_Size() int {
	return xxx_messageInfo_ManyToManyOptions.Size(m)
}
func (m *ManyToManyOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ManyToManyOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ManyToManyOptions proto.InternalMessageInfo

func (m *ManyToManyOptions) GetJointable() string {
	if m != nil {
		return m.Jointable
	}
	return ""
}

func (m *ManyToManyOptions) GetForeignkey() string {
	if m != nil {
		return m.Foreignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetJointableForeignkey() string {
	if m != nil {
		return m.JointableForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationForeignkey() string {
	if m != nil {
		return m.AssociationForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationJointableForeignkey() string {
	if m != nil {
		return m.AssociationJointableForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationAutoupdate() bool {
	if m != nil {
		return m.AssociationAutoupdate
	}
	return false
}

func (m *ManyToManyOptions) GetAssociationAutocreate() bool {
	if m != nil {
		return m.AssociationAutocreate
	}
	return false
}

func (m *ManyToManyOptions) GetAssociationSaveReference() bool {
	if m != nil {
		return m.AssociationSaveReference
	}
	return false
}

func (m *ManyToManyOptions) GetPreload() bool {
	if m != nil {
		return m.Preload
	}
	return false
}

func (m *ManyToManyOptions) GetReplace() bool {
	if m != nil {
		return m.Replace
	}
	return false
}

func (m *ManyToManyOptions) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

func (m *ManyToManyOptions) GetClear() bool {
	if m != nil {
		return m.Clear
	}
	return false
}

type AutoServerOptions struct {
	Autogen              bool     `protobuf:"varint,1,opt,name=autogen,proto3" json:"autogen,omitempty"`
	TxnMiddleware        bool     `protobuf:"varint,2,opt,name=txn_middleware,json=txnMiddleware,proto3" json:"txn_middleware,omitempty"`
	WithTracing          bool     `protobuf:"varint,3,opt,name=with_tracing,json=withTracing,proto3" json:"with_tracing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoServerOptions) Reset()         { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()    {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{9}
}
func (m *AutoServerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoServerOptions.Unmarshal(m, b)
}
func (m *AutoServerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoServerOptions.Marshal(b, m, deterministic)
}
func (m *AutoServerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoServerOptions.Merge(m, src)
}
func (m *AutoServerOptions) XXX_Size() int {
	return xxx_messageInfo_AutoServerOptions.Size(m)
}
func (m *AutoServerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoServerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AutoServerOptions proto.InternalMessageInfo

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil {
		return m.Autogen
	}
	return false
}

func (m *AutoServerOptions) GetTxnMiddleware() bool {
	if m != nil {
		return m.TxnMiddleware
	}
	return false
}

func (m *AutoServerOptions) GetWithTracing() bool {
	if m != nil {
		return m.WithTracing
	}
	return false
}

type MethodOptions struct {
	ObjectType           string   `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7901ada31e8ac2ce, []int{10}
}
func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*OrmFileOptions)(nil),
	Field:         52120,
	Name:          "orm.file_opts",
	Tag:           "bytes,52120,opt,name=file_opts",
	Filename:      "protoc-gen-orm/orm/orm.proto",
}

var E_Ormable = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         52120,
	Name:          "orm.ormable",
	Tag:           "varint,52120,opt,name=ormable",
	Filename:      "protoc-gen-orm/orm/orm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*OrmFieldOptions)(nil),
	Field:         52120,
	Name:          "orm.field",
	Tag:           "bytes,52120,opt,name=field",
	Filename:      "protoc-gen-orm/orm/orm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         52120,
	Name:          "orm.server",
	Tag:           "bytes,52120,opt,name=server",
	Filename:      "protoc-gen-orm/orm/orm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         52120,
	Name:          "orm.method",
	Tag:           "bytes,52120,opt,name=method",
	Filename:      "protoc-gen-orm/orm/orm.proto",
}

func init() {
	proto.RegisterType((*OrmFileOptions)(nil), "orm.OrmFileOptions")
	proto.RegisterType((*OrmMessageOptions)(nil), "orm.OrmMessageOptions")
	proto.RegisterType((*ExtraField)(nil), "orm.ExtraField")
	proto.RegisterType((*OrmFieldOptions)(nil), "orm.OrmFieldOptions")
	proto.RegisterType((*OrmTag)(nil), "orm.OrmTag")
	proto.RegisterType((*HasOneOptions)(nil), "orm.HasOneOptions")
	proto.RegisterType((*BelongsToOptions)(nil), "orm.BelongsToOptions")
	proto.RegisterType((*HasManyOptions)(nil), "orm.HasManyOptions")
	proto.RegisterType((*ManyToManyOptions)(nil), "orm.ManyToManyOptions")
	proto.RegisterType((*AutoServerOptions)(nil), "orm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "orm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Ormable)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("protoc-gen-orm/orm/orm.proto", fileDescriptor_7901ada31e8ac2ce) }

var fileDescriptor_7901ada31e8ac2ce = []byte{
	// 1220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0xf1, 0x4f, 0xec, 0xe3, 0xd8, 0x49, 0xa6, 0x69, 0x58, 0xaa, 0xfe, 0x04, 0xa3, 0x42,
	0xb8, 0xa8, 0x53, 0x82, 0x40, 0x22, 0x20, 0xa4, 0x56, 0xa2, 0x6a, 0x29, 0xc1, 0x65, 0x9b, 0x2b,
	0x6e, 0x56, 0xe3, 0xdd, 0x63, 0x67, 0xda, 0xdd, 0x99, 0x65, 0x76, 0x36, 0x8d, 0x79, 0x02, 0x24,
	0x2e, 0x7b, 0x01, 0x8f, 0xc0, 0xbb, 0x20, 0x9e, 0x82, 0x17, 0x41, 0x33, 0xb3, 0x7f, 0x8e, 0xed,
	0x2a, 0x0a, 0x5c, 0x20, 0xc1, 0xc5, 0x4a, 0x7b, 0xbe, 0x39, 0xe7, 0xcc, 0xf9, 0x9d, 0x99, 0x03,
	0x37, 0x63, 0x29, 0x94, 0xf0, 0xef, 0x4d, 0x91, 0xdf, 0x13, 0x32, 0x3a, 0xc8, 0xbe, 0xa1, 0x81,
	0x49, 0x5d, 0xc8, 0xe8, 0xc6, 0xde, 0x54, 0x88, 0x69, 0x88, 0x07, 0x06, 0x1a, 0xa7, 0x93, 0x83,
	0x00, 0x13, 0x5f, 0xb2, 0x58, 0x09, 0x69, 0xd9, 0x06, 0x5b, 0xd0, 0x1f, 0xc9, 0xe8, 0x11, 0x0b,
	0x71, 0x14, 0x2b, 0x26, 0x78, 0x32, 0x78, 0x5d, 0x83, 0xed, 0x91, 0x8c, 0x8e, 0x31, 0x49, 0xe8,
	0x34, 0x47, 0x89, 0x03, 0xeb, 0x42, 0x46, 0x74, 0x1c, 0xa2, 0x53, 0xdb, 0xab, 0xed, 0xb7, 0xdd,
	0x9c, 0x24, 0x1f, 0xc2, 0x3a, 0xe3, 0x7e, 0x98, 0x06, 0xe8, 0xac, 0xed, 0xd5, 0xf7, 0xbb, 0x87,
	0x9b, 0x43, 0x6d, 0xc5, 0x57, 0xe7, 0x4a, 0xd2, 0x47, 0x0c, 0xc3, 0xc0, 0xcd, 0xd7, 0xc9, 0x0e,
	0x34, 0x95, 0x51, 0x51, 0xdf, 0xab, 0xed, 0x77, 0x5c, 0x4b, 0x90, 0xf7, 0xa0, 0x17, 0xa5, 0xa1,
	0x62, 0x1e, 0xf5, 0x7d, 0x91, 0x72, 0xe5, 0x34, 0xcc, 0x06, 0x1b, 0x06, 0x7c, 0x60, 0xb1, 0x41,
	0x04, 0x50, 0x6a, 0x24, 0x04, 0x1a, 0x6a, 0x16, 0x5b, 0x53, 0x3a, 0xae, 0xf9, 0xd7, 0x18, 0xa7,
	0x91, 0x36, 0xc2, 0x60, 0xfa, 0x9f, 0xdc, 0x82, 0xba, 0xa2, 0x53, 0xb3, 0x5d, 0xf7, 0xb0, 0x6b,
	0xec, 0x1a, 0xc9, 0xe8, 0x84, 0x4e, 0x5d, 0x8d, 0x6b, 0xa7, 0x62, 0xea, 0xbf, 0xa4, 0x53, 0x34,
	0x7b, 0x76, 0xdc, 0x9c, 0x1c, 0xfc, 0xbe, 0x06, 0x9b, 0x26, 0x2e, 0x18, 0x06, 0x79, 0x08, 0x32,
	0x65, 0xb5, 0x15, 0xca, 0x08, 0x34, 0x02, 0x29, 0x62, 0xb3, 0x7f, 0xdb, 0x35, 0xff, 0xe4, 0x1e,
	0xac, 0x9f, 0xd2, 0xc4, 0x13, 0x1c, 0x33, 0x1b, 0x88, 0x11, 0x7b, 0x4c, 0x93, 0x11, 0xcf, 0x43,
	0xfb, 0xf8, 0x2d, 0xb7, 0x75, 0x6a, 0x00, 0xf2, 0x29, 0xc0, 0x18, 0x43, 0xc1, 0xa7, 0x89, 0xa7,
	0x84, 0x31, 0xa9, 0x7b, 0x78, 0xdd, 0x48, 0x3c, 0xb4, 0xf0, 0x89, 0x28, 0x85, 0x3a, 0xe3, 0x1c,
	0x23, 0xf7, 0xa1, 0xad, 0xb7, 0x89, 0x28, 0x9f, 0x39, 0x4d, 0x23, 0x75, 0x2d, 0xdf, 0xe7, 0x98,
	0xf2, 0x59, 0x29, 0xa3, 0xad, 0xd1, 0x08, 0x39, 0x82, 0x0d, 0xcd, 0xed, 0x29, 0x61, 0xa5, 0x5a,
	0x46, 0x6a, 0xd7, 0x48, 0x69, 0x86, 0x13, 0x31, 0x2f, 0x08, 0x51, 0x01, 0x92, 0x77, 0x61, 0x43,
	0xe2, 0x04, 0x25, 0x72, 0x1f, 0x3d, 0x31, 0x71, 0xd6, 0x4d, 0xe8, 0xba, 0x05, 0x36, 0x9a, 0x3c,
	0xec, 0x41, 0x97, 0x26, 0x89, 0xf0, 0x19, 0xd5, 0x0a, 0x06, 0x7f, 0xb4, 0xa0, 0x65, 0x43, 0x45,
	0x76, 0xa1, 0xe5, 0x8b, 0x30, 0x8d, 0x78, 0x96, 0xbb, 0x8c, 0x2a, 0x32, 0xba, 0x36, 0x9f, 0xd1,
	0x84, 0xfd, 0x68, 0x43, 0xd7, 0x74, 0xcd, 0x3f, 0xb9, 0x09, 0x9d, 0x58, 0xa2, 0xcf, 0x12, 0x26,
	0xb8, 0x89, 0x50, 0xd3, 0x2d, 0x01, 0x72, 0x07, 0xba, 0xb1, 0x64, 0x11, 0x95, 0x33, 0xef, 0x25,
	0xda, 0x58, 0xb4, 0x5d, 0xc8, 0xa0, 0xa7, 0x38, 0xd3, 0xdb, 0xa7, 0x9c, 0xfd, 0x90, 0xa2, 0xf1,
	0xb8, 0xed, 0x66, 0x94, 0xae, 0x84, 0x00, 0x27, 0x34, 0x0d, 0x55, 0xe6, 0x4e, 0x4e, 0x92, 0x77,
	0xa0, 0xcd, 0x85, 0xf2, 0x78, 0x1a, 0x86, 0x4e, 0xdb, 0x56, 0x3e, 0x17, 0xea, 0xdb, 0x34, 0x0c,
	0xc9, 0x5d, 0xe8, 0xd3, 0x54, 0x09, 0x8f, 0x71, 0x5f, 0x62, 0x84, 0x5c, 0x39, 0x1d, 0xc3, 0xd0,
	0xd3, 0xe8, 0x93, 0x1c, 0xd4, 0x55, 0xcf, 0x78, 0x80, 0xe7, 0x0e, 0xd8, 0xaa, 0x37, 0x84, 0x8e,
	0xa2, 0xdd, 0xdb, 0xb3, 0x8b, 0x5d, 0x1b, 0x45, 0x8b, 0x3d, 0x31, 0x2c, 0x37, 0xa0, 0x8d, 0xd1,
	0x18, 0x83, 0x00, 0x03, 0x67, 0xc3, 0x68, 0x2e, 0x68, 0xf2, 0x01, 0x6c, 0xe6, 0xff, 0x5e, 0x2c,
	0x71, 0xc2, 0xce, 0x9d, 0x9e, 0xd1, 0xd0, 0xcf, 0xe1, 0x67, 0x06, 0xd5, 0x1e, 0xb3, 0x29, 0x17,
	0x12, 0x9d, 0xbe, 0xf5, 0xd8, 0x52, 0xe4, 0x36, 0xc0, 0x44, 0x48, 0x64, 0x53, 0xae, 0x23, 0xb5,
	0x69, 0x64, 0x2b, 0x08, 0xf9, 0x04, 0x76, 0x2b, 0x29, 0xf4, 0x2a, 0xbc, 0x5b, 0x86, 0xf7, 0x7a,
	0x65, 0xf5, 0x51, 0x29, 0xb6, 0x77, 0xa1, 0xb0, 0xb6, 0xad, 0xe2, 0x4a, 0xf9, 0x7c, 0x04, 0x3b,
	0x2f, 0x04, 0xe3, 0xa6, 0xf7, 0xab, 0x6a, 0x89, 0xe1, 0xbc, 0x56, 0xac, 0x55, 0x94, 0x3e, 0x86,
	0xbd, 0xaa, 0x2d, 0x4b, 0xc5, 0xaf, 0x19, 0xf1, 0xdb, 0x15, 0xbe, 0xaf, 0x97, 0x68, 0xba, 0xe0,
	0x95, 0x4e, 0x54, 0x1a, 0x07, 0x54, 0xa1, 0xb3, 0x63, 0xa2, 0x53, 0xf5, 0xea, 0x41, 0xb1, 0xb8,
	0x4c, 0xcc, 0x97, 0xa8, 0xc5, 0xae, 0x2f, 0x15, 0xb3, 0x8b, 0xe4, 0x0b, 0xb8, 0x51, 0x15, 0x4b,
	0xe8, 0x19, 0x7a, 0x45, 0x9b, 0x38, 0xbb, 0x46, 0xd4, 0xa9, 0x70, 0x3c, 0xa7, 0x67, 0xe8, 0xe6,
	0xeb, 0xe6, 0x74, 0x92, 0x18, 0x0a, 0x1a, 0x38, 0x6f, 0xdb, 0xc2, 0xcb, 0xc8, 0xc1, 0x6f, 0x75,
	0xe8, 0xcd, 0x9d, 0x21, 0x17, 0xb2, 0x59, 0x5b, 0xc8, 0xe6, 0x21, 0xf4, 0x4b, 0xca, 0xd3, 0xc7,
	0xd8, 0xda, 0xe2, 0x31, 0xd6, 0x2b, 0x59, 0x74, 0xab, 0xae, 0xae, 0x80, 0xfa, 0x9b, 0x2a, 0x60,
	0x75, 0x88, 0x1b, 0x57, 0x0b, 0x71, 0xf3, 0xea, 0x21, 0x6e, 0x5d, 0x3e, 0xc4, 0xeb, 0x73, 0x21,
	0xd6, 0x2b, 0x12, 0xe3, 0x90, 0xfa, 0x98, 0x77, 0x7d, 0x46, 0xea, 0x86, 0xa2, 0x71, 0x8c, 0x3c,
	0xc8, 0xba, 0x3d, 0xa3, 0x74, 0x9b, 0xfb, 0x21, 0x52, 0x69, 0xda, 0xbc, 0xed, 0x5a, 0x62, 0xf0,
	0xe7, 0x1a, 0x6c, 0x5d, 0x3c, 0xbc, 0xff, 0xcf, 0xd6, 0x3f, 0x9c, 0xad, 0xc1, 0xcf, 0x0d, 0xe8,
	0xcf, 0x5f, 0x76, 0xff, 0xa6, 0x18, 0xdf, 0x85, 0x7e, 0x2c, 0x12, 0x66, 0x65, 0xf4, 0x8b, 0x22,
	0x7b, 0x6d, 0xf4, 0x72, 0xd4, 0x3e, 0x6a, 0x3e, 0x03, 0x32, 0xcf, 0x66, 0xac, 0x6a, 0x2e, 0x5a,
	0xb5, 0x35, 0x27, 0xb7, 0xc4, 0xb0, 0x4a, 0x16, 0x5b, 0x57, 0xcb, 0xe2, 0xfa, 0xd5, 0xb3, 0xd8,
	0xbe, 0x7c, 0x16, 0x3b, 0x2b, 0x7b, 0x0e, 0x56, 0xf5, 0x5c, 0x77, 0x79, 0xcf, 0x6d, 0x54, 0x7b,
	0xee, 0x75, 0x03, 0xb6, 0x17, 0x1e, 0x31, 0xfa, 0xe5, 0x50, 0x5c, 0x1c, 0x59, 0x3d, 0x94, 0xc0,
	0x85, 0x72, 0x59, 0x5b, 0x28, 0x97, 0x55, 0xb7, 0x56, 0x7d, 0xf5, 0xad, 0xb5, 0xba, 0x5a, 0x1a,
	0x6f, 0xaa, 0x96, 0xcb, 0x5c, 0x76, 0xcd, 0xbf, 0x79, 0xd9, 0xfd, 0x47, 0xaa, 0xa2, 0x57, 0xad,
	0x8a, 0x57, 0xb0, 0xad, 0xad, 0x7d, 0x8e, 0xf2, 0x0c, 0x65, 0x65, 0xac, 0xd1, 0xfe, 0x4d, 0x91,
	0xe7, 0x63, 0x4d, 0x46, 0xea, 0xa6, 0x55, 0xe7, 0xdc, 0x8b, 0x58, 0x10, 0x84, 0xf8, 0x8a, 0x4a,
	0xcc, 0x1e, 0xf6, 0x3d, 0x75, 0xce, 0x8f, 0x0b, 0x50, 0x3f, 0xe3, 0x5e, 0x31, 0x75, 0xea, 0x29,
	0x49, 0x7d, 0xc6, 0xed, 0xa8, 0xd1, 0x76, 0xbb, 0x1a, 0x3b, 0xb1, 0xd0, 0xe0, 0x3e, 0xf4, 0x8e,
	0x51, 0x9d, 0x8a, 0x62, 0x90, 0xb8, 0x03, 0x5d, 0x31, 0x7e, 0x81, 0xbe, 0xf2, 0x2a, 0x43, 0x0c,
	0x58, 0xe8, 0x64, 0x16, 0xe3, 0xd1, 0x33, 0xe8, 0x4c, 0x58, 0x88, 0x9e, 0x88, 0x55, 0x42, 0x6e,
	0x0e, 0xed, 0x10, 0x37, 0xcc, 0x87, 0xb8, 0x61, 0x65, 0x5a, 0x73, 0x7e, 0xfd, 0xa5, 0x5e, 0x79,
	0xf0, 0xcf, 0x8f, 0x72, 0x6e, 0x7b, 0x62, 0x89, 0xe4, 0xe8, 0xcb, 0x62, 0x7c, 0x23, 0x77, 0x16,
	0xf4, 0xcd, 0x8f, 0x7a, 0x99, 0xca, 0x72, 0xc2, 0xfb, 0xa9, 0x56, 0x3b, 0x7a, 0x0a, 0x4d, 0x73,
	0x24, 0x91, 0x5b, 0x4b, 0xac, 0x29, 0x67, 0xa4, 0xc2, 0x9c, 0x9d, 0xd2, 0x9c, 0x72, 0xd5, 0xb5,
	0x3a, 0x8e, 0xbe, 0x83, 0x56, 0x62, 0xb2, 0xb0, 0xc4, 0x16, 0x9d, 0x1e, 0xe6, 0x2f, 0xb8, 0x67,
	0x27, 0x93, 0x85, 0xfc, 0xb9, 0x99, 0xa2, 0xa3, 0x6f, 0xa0, 0x15, 0x99, 0x18, 0x93, 0xdb, 0x4b,
	0xdc, 0xab, 0x04, 0xbf, 0xd0, 0x68, 0x27, 0xb1, 0xb9, 0x35, 0x37, 0xd3, 0xf1, 0x70, 0xff, 0xfb,
	0xf7, 0xed, 0x6c, 0x3d, 0x9c, 0xcd, 0x52, 0x1c, 0x06, 0x78, 0x76, 0xb0, 0x38, 0x6b, 0x7f, 0x2e,
	0x64, 0x34, 0x6e, 0x19, 0xfc, 0xe3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0xf2, 0x28, 0xe3,
	0x8c, 0x0f, 0x00, 0x00,
}
