// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protoc-gen-orm/test.proto

package pbconf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mozyy/empty-news/proto/pbconf2"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	_ "protoc.yyue.dev/protoc-gen-orm/orm"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConfigORM struct {
	ID        uint32 `gorm:"primary_key";`
	Desc      string
	Type      string
	Value     string
	Content   string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time `gorm:"index";`
}
type DeleteTypeORM struct {
	Id uint32
}
