// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protoc-gen-orm/test.proto

package pbconf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
