// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: config/test2.proto

// import "protoc-gen-orm/orm/orm.proto";

package pbconf2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteType2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// option (orm.ormable) = true;
	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteType2) Reset() {
	*x = DeleteType2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_test2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteType2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteType2) ProtoMessage() {}

func (x *DeleteType2) ProtoReflect() protoreflect.Message {
	mi := &file_config_test2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteType2.ProtoReflect.Descriptor instead.
func (*DeleteType2) Descriptor() ([]byte, []int) {
	return file_config_test2_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteType2) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_config_test2_proto protoreflect.FileDescriptor

var file_config_test2_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x32, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x6f, 0x6e, 0x66, 0x32, 0x22, 0x1d, 0x0a, 0x0b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x7a, 0x79, 0x79, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2d, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x32, 0x3b, 0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x32, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_test2_proto_rawDescOnce sync.Once
	file_config_test2_proto_rawDescData = file_config_test2_proto_rawDesc
)

func file_config_test2_proto_rawDescGZIP() []byte {
	file_config_test2_proto_rawDescOnce.Do(func() {
		file_config_test2_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_test2_proto_rawDescData)
	})
	return file_config_test2_proto_rawDescData
}

var file_config_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_test2_proto_goTypes = []interface{}{
	(*DeleteType2)(nil), // 0: conf2.DeleteType2
}
var file_config_test2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_test2_proto_init() }
func file_config_test2_proto_init() {
	if File_config_test2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_test2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteType2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_test2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_test2_proto_goTypes,
		DependencyIndexes: file_config_test2_proto_depIdxs,
		MessageInfos:      file_config_test2_proto_msgTypes,
	}.Build()
	File_config_test2_proto = out.File
	file_config_test2_proto_rawDesc = nil
	file_config_test2_proto_goTypes = nil
	file_config_test2_proto_depIdxs = nil
}
