name: gen proto

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proto
        uses: actions/checkout@v3
        with:
          path: empty-proto

      - name: Checkout empty-news
        uses: actions/checkout@v3
        with:
          repository: mozyy/empty-news
          path: empty-news
          ref: proto

      - name: Checkout empty-frontend-ng
        uses: actions/checkout@v3
        with:
          repository: mozyy/empty-frontend-ng
          path: empty-frontend-ng
          ref: proto

      - uses: bufbuild/buf-setup-action@v1
      - run: |
          pwd
          ls
          ls empty-proto
          go version

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: empty-proto/proto
      
      - uses: actions/setup-go@v3
          # go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: |
          go version
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/mozyy/protoc-gen-gorm@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
          echo $PATH
          echo "`go env GOPATH`/bin" >> $GITHUB_PATH
          echo $PATH
          whereis go
          ls /usr/bin/go
          go env GOPATH
          ls /home/runner/go
          ls /home/runner/go/bin
      - run: |
          echo $PATH
          buf generate proto
        working-directory: empty-proto
      - run: |
          git status
          git add .
          git commit -m 'update proto'
          git push origin proto
        working-directory: empty-news